version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    reviewers:
      - "alfin-efendy"
    assignees:
      - "alfin-efendy"
    open-pull-requests-limit: 5

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "06:00"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "alfin-efendy"
    assignees:
      - "alfin-efendy"
    open-pull-requests-limit: 3

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    commit-message:
      prefix: "docker"
      include: "scope"
    reviewers:
      - "alfin-efendy"
    assignees:
      - "alfin-efendy"
    open-pull-requests-limit: 2