package bundler

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestGenerateBundle(t *testing.T) {
	b, err := NewBundler("test.lua", false, false)
	require.NoError(t, err, "NewBundler should not fail")

	// Add some test modules
	b.modules["./helper.lua"] = `local helper = {}
function helper.greet()
    return "Hello"
end
return helper`

	b.modules["https://example.com/remote.lua"] = `local remote = {}
function remote.fetch()
    return "data"
end
return remote`

	rawContent := `local helper = require('./helper.lua')
local remote = loadstring(game:HttpGet('https://example.com/remote.lua'))()

print(helper.greet())
print(remote.fetch())`

	// Simulate the pipeline: rewrite calls before passing to generateBundle.
	mainContent := b.rewriteModuleCalls(rawContent, "test.lua")
	result := b.generateBundle(mainContent)

	tests := []struct {
		name    string
		check   func(string) bool
		message string
	}{
		{
			name: "contains bundle header",
			check: func(s string) bool {
				return strings.Contains(s, "-- Bundled Lua Script") &&
					strings.Contains(s, "-- Generated by Lua Bundler")
			},
			message: "should contain bundle header",
		},
		{
			name: "contains EmbeddedModules table",
			check: func(s string) bool {
				return strings.Contains(s, "local EmbeddedModules = {}")
			},
			message: "should contain EmbeddedModules table",
		},
		{
			name: "contains loadModule function",
			check: func(s string) bool {
				return strings.Contains(s, "local function loadModule(url)")
			},
			message: "should contain loadModule function",
		},
		{
			name: "contains helper module",
			check: func(s string) bool {
				return strings.Contains(s, `EmbeddedModules["./helper.lua"]`) &&
					strings.Contains(s, "function helper.greet()")
			},
			message: "should contain helper module",
		},
		{
			name: "contains remote module",
			check: func(s string) bool {
				return strings.Contains(s, `EmbeddedModules["https://example.com/remote.lua"]`) &&
					strings.Contains(s, "function remote.fetch()")
			},
			message: "should contain remote module",
		},
		{
			name: "replaces require calls",
			check: func(s string) bool {
				// rewriteModuleCalls uses canonical keys (no leading "./" or ".lua" suffix).
				return strings.Contains(s, `loadModule("helper")`) &&
					!strings.Contains(s, `require('./helper.lua')`)
			},
			message: "should replace require calls with loadModule",
		},
		{
			name: "replaces loadstring calls",
			check: func(s string) bool {
				return strings.Contains(s, `loadModule("https://example.com/remote.lua")`) &&
					!strings.Contains(s, `loadstring(game:HttpGet('https://example.com/remote.lua'))()`)
			},
			message: "should replace loadstring calls with loadModule",
		},
		{
			name: "contains main script section",
			check: func(s string) bool {
				return strings.Contains(s, "-- Main Script")
			},
			message: "should contain main script section",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.True(t, tt.check(result), "generateBundle() %s", tt.message)
		})
	}
}

func TestEscapeString(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected string
	}{
		{
			name:     "simple string",
			input:    "hello",
			expected: "hello",
		},
		{
			name:     "string with quotes",
			input:    `hello "world"`,
			expected: `hello \"world\"`,
		},
		{
			name:     "string with backslashes",
			input:    `path\to\file`,
			expected: `path\\to\\file`,
		},
		{
			name:     "string with both quotes and backslashes",
			input:    `"C:\Program Files\App"`,
			expected: `\"C:\\Program Files\\App\"`,
		},
		{
			name:     "empty string",
			input:    "",
			expected: "",
		},
		{
			name:     "URL with protocol",
			input:    "https://example.com/path?param=value",
			expected: "https://example.com/path?param=value",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := escapeString(tt.input)
			assert.Equal(t, tt.expected, result, "escapeString() result should match expected")
		})
	}
}

func TestGenerateBundle_EmptyModules(t *testing.T) {
	b, err := NewBundler("test.lua", false, false)
	require.NoError(t, err, "NewBundler should not fail")
	// No modules added

	mainContent := `print("Hello World")`

	result := b.generateBundle(mainContent)

	// Should still generate valid structure even with no modules
	assert.Contains(t, result, "local EmbeddedModules = {}", "generateBundle() should contain EmbeddedModules table even with no modules")
	assert.Contains(t, result, "local function loadModule(url)", "generateBundle() should contain loadModule function even with no modules")
	assert.Contains(t, result, "-- Main Script", "generateBundle() should contain main script section")
	assert.Contains(t, result, `print("Hello World")`, "generateBundle() should contain original main content")
}

func TestGenerateBundle_InjectsDecoderAtLevel3(t *testing.T) {
	b, err := NewBundler("test.lua", false, false)
	require.NoError(t, err)
	b.SetObfuscationLevel(3)
	out := b.generateBundle(`return 1`)

	// Decoder defined exactly once, before EmbeddedModules.
	if strings.Count(out, "local _d=") != 1 {
		t.Fatalf("expected exactly one _d decoder, got %d:\n%s", strings.Count(out, "local _d="), out)
	}
	di := strings.Index(out, "local _d=")
	ei := strings.Index(out, "local EmbeddedModules")
	if di < 0 || ei < 0 || di > ei {
		t.Fatalf("decoder must precede EmbeddedModules (d=%d, e=%d)", di, ei)
	}
}

func TestGenerateBundle_NoDecoderBelowLevel3(t *testing.T) {
	b, err := NewBundler("test.lua", false, false)
	require.NoError(t, err)
	b.SetObfuscationLevel(2)
	out := b.generateBundle(`return 1`)
	if strings.Contains(out, "local _d=") {
		t.Fatalf("level 2 bundle must not contain a decoder:\n%s", out)
	}
}

func TestGenerateBundle_ModuleIndentation(t *testing.T) {
	b, err := NewBundler("test.lua", false, false)
	require.NoError(t, err, "NewBundler should not fail")

	moduleContent := `local test = {}

function test.method()
    if true then
        print("nested")
    end
end

return test`

	b.modules["test"] = moduleContent

	result := b.generateBundle("local t = require('test')")

	// Check that indentation is properly added (4 spaces for each line)
	lines := strings.Split(result, "\n")
	moduleStarted := false
	moduleEnded := false

	for _, line := range lines {
		if strings.Contains(line, `EmbeddedModules["test"] = function()`) {
			moduleStarted = true
			continue
		}

		if moduleStarted && !moduleEnded {
			if strings.TrimSpace(line) == "end" && !strings.HasPrefix(line, "    ") {
				moduleEnded = true
				continue
			}

			// Non-empty lines in module should be indented with 4 spaces
			if strings.TrimSpace(line) != "" {
				assert.True(t, strings.HasPrefix(line, "    "), "Module line should be indented with 4 spaces: %q", line)
			}
		}
	}
}

func TestRewriteModuleCalls_ModuleBodyCanonical(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(dir, "core"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(dir, "components"), 0o755))
	for _, p := range []string{"main.lua", "core/theme.lua", "components/button.lua"} {
		require.NoError(t, os.WriteFile(filepath.Join(dir, p), []byte("return {}"), 0o644))
	}
	b, err := NewBundler(filepath.Join(dir, "main.lua"), false, false)
	require.NoError(t, err)

	button := filepath.Join(dir, "components/button.lua")
	// button.lua requires the shared core/theme via a relative path
	got := b.rewriteModuleCalls(`local T = require("../core/theme")`, button)
	if !strings.Contains(got, `loadModule("core/theme")`) {
		t.Fatalf("module-body require not rewritten to canonical loadModule: %q", got)
	}
}

func TestRewriteModuleCalls_SkipsFunctionWrappedHttpGet(t *testing.T) {
	b, err := NewBundler("x.lua", false, false)
	require.NoError(t, err)
	in := `queue_on_teleport("loadstring(game:HttpGet('https://e/x.lua'))()")`
	if got := b.rewriteModuleCalls(in, "x.lua"); got != in {
		t.Fatalf("function-wrapped HttpGet must NOT be rewritten: %q", got)
	}
}

func TestRewriteModuleCalls_DirectHttpGet(t *testing.T) {
	b, err := NewBundler("x.lua", false, false)
	require.NoError(t, err)
	in := `loadstring(game:HttpGet("https://e/x.lua"))()`
	got := b.rewriteModuleCalls(in, "x.lua")
	if !strings.Contains(got, `loadModule("https://e/x.lua")`) {
		t.Fatalf("direct HttpGet must be rewritten: %q", got)
	}
}
