package bundler

import (
	"fmt"
	"regexp"
	"strings"
)

// Module-call detection patterns, compiled once and shared by discovery
// (processFile) and rewriting (rewriteModuleCalls).
var (
	moduleRequireRegex    = regexp.MustCompile(`require\s*\(\s*['"]([^'"]+)['"]\s*\)`)
	moduleHTTPGetRegex    = regexp.MustCompile(`loadstring\s*\(\s*game:HttpGet\s*\(\s*['"]([^'"]+)['"]\s*\)\s*\)\s*\(\s*\)`)
	moduleFuncWrapHTTPGet = regexp.MustCompile(`\w+\s*\([^)]*loadstring\s*\(\s*game:HttpGet`)
)

// generateBundle creates the final bundled output
func (b *Bundler) generateBundle(mainContent string) string {
	var output strings.Builder

	output.WriteString("-- Bundled Lua Script\n")
	output.WriteString("-- Generated by Lua Bundler\n")
	output.WriteString("-- https://github.com/alfin-efendy/lua-bundler\n\n")

	// Inject the level-3 string-decoder once, before any module closure that
	// references it (closures capture _d as an upvalue).
	if b.obfuscateLevel >= 3 && b.obfuscator != nil {
		if prelude := b.obfuscator.DecoderPrelude(); prelude != "" {
			output.WriteString(prelude)
			output.WriteString("\n\n")
		}
	}

	// Generate EmbeddedModules table
	output.WriteString("local EmbeddedModules = {}\n\n")

	// Add all modules
	for path, content := range b.modules {
		output.WriteString(fmt.Sprintf("-- Module: %s\n", path))
		output.WriteString(fmt.Sprintf("EmbeddedModules[\"%s\"] = function()\n", escapeString(path)))

		// Indent content
		lines := strings.Split(content, "\n")
		for _, line := range lines {
			if strings.TrimSpace(line) != "" {
				output.WriteString("    " + line + "\n")
			} else {
				output.WriteString("\n")
			}
		}

		output.WriteString("end\n\n")
	}

	// Add loadModule function
	output.WriteString("-- Load module helper function\n")
	output.WriteString("local function loadModule(url)\n")
	output.WriteString("    -- Try embedded module first\n")
	output.WriteString("    if EmbeddedModules[url] then\n")
	output.WriteString("        return EmbeddedModules[url]()\n")
	output.WriteString("    end\n")
	output.WriteString("    \n")
	output.WriteString("    -- Fallback to original require\n")
	output.WriteString("    return require(url)\n")
	output.WriteString("end\n\n")

	output.WriteString("-- Main Script\n")
	output.WriteString(mainContent)

	return output.String()
}

// rewriteModuleCalls rewrites local require() and direct loadstring(HttpGet())()
// calls in content into loadModule(canonicalKey) calls. currentFile gives the
// caller's location so relative require paths resolve to canonical keys. It runs
// on raw (pre-obfuscation) source, so the function-wrapped-HttpGet skip is
// evaluated on readable, multi-line text.
func (b *Bundler) rewriteModuleCalls(content, currentFile string) string {
	processed := content

	// Replace direct loadstring(game:HttpGet(url))() — skip lines where it's wrapped in a call.
	lines := strings.Split(processed, "\n")
	for i, line := range lines {
		if moduleFuncWrapHTTPGet.MatchString(line) {
			continue
		}
		lines[i] = moduleHTTPGetRegex.ReplaceAllStringFunc(line, func(match string) string {
			m := moduleHTTPGetRegex.FindStringSubmatch(match)
			if len(m) > 1 {
				return fmt.Sprintf("loadModule(\"%s\")", escapeString(m[1]))
			}
			return match
		})
	}
	processed = strings.Join(lines, "\n")

	// Replace local require() with loadModule(canonicalKey).
	processed = moduleRequireRegex.ReplaceAllStringFunc(processed, func(match string) string {
		m := moduleRequireRegex.FindStringSubmatch(match)
		if len(m) > 1 && b.isLocalModule(m[1]) {
			return fmt.Sprintf("loadModule(\"%s\")", escapeString(b.canonicalKey(currentFile, m[1])))
		}
		return match
	})

	return processed
}

// escapeString escapes special characters in strings for Lua
func escapeString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	return s
}
